name = "cloudflare-worker-cosmos-auth"
main = "src/index.ts"
compatibility_date = "2022-11-16"
node_compat = true

kv_namespaces = [
  { binding = "NONCES", id = "f68fbe33b7b44ad09bed1c29e7186f12", preview_id = "9817484e78b14c3385cb6483695f210f" }
]
